CREATE TABLE eft_producto (
    producto_id        NUMBER GENERATED BY DEFAULT AS IDENTITY
                       PRIMARY KEY,
    sku                VARCHAR2(50)    NOT NULL UNIQUE,
    nombre             VARCHAR2(150)   NOT NULL,
    descripcion        CLOB,
    precio             NUMBER(18,2)    NOT NULL,      -- sin código de divisa
    cantidad_stock     NUMBER          NOT NULL,
    creado_en          TIMESTAMP WITH TIME ZONE
                       DEFAULT SYSTIMESTAMP NOT NULL,
    actualizado_en     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE eft_carrito (
    carrito_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     VARCHAR2(255),                    -- GUID de Azure AD
    estado         CHAR(1) DEFAULT 'A' NOT NULL,     -- A=Activo, C=Completado, X=Abandonado
    creado_en      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    actualizado_en TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_carrito_estado CHECK (estado IN ('A','C','X'))
);

CREATE INDEX ix_carrito_usuario_estado ON eft_carrito (usuario_id, estado);

CREATE TABLE eft_carrito_item (
    carrito_item_id    NUMBER GENERATED BY DEFAULT AS IDENTITY
                       PRIMARY KEY,
    carrito_id         NUMBER         NOT NULL,
    producto_id        NUMBER         NOT NULL,
    cantidad           NUMBER         NOT NULL,
    precio_unitario    NUMBER(18,2)   NOT NULL,       -- precio “congelado” al añadir
    agregado_en        TIMESTAMP WITH TIME ZONE
                       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_ci_carrito
        FOREIGN KEY (carrito_id)
        REFERENCES eft_carrito (carrito_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_ci_producto
        FOREIGN KEY (producto_id)
        REFERENCES eft_producto (producto_id),

    CONSTRAINT ck_ci_cantidad
        CHECK (cantidad > 0)
);

CREATE UNIQUE INDEX ux_ci_carrito_producto
    ON eft_carrito_item (carrito_id, producto_id);

CREATE TABLE eft_ventas (
    venta_id           NUMBER GENERATED BY DEFAULT AS IDENTITY
                       PRIMARY KEY,
    carrito_id         NUMBER         NOT NULL UNIQUE,
    usuario_id         VARCHAR2(255),                 -- GUID de Azure AD
    monto_total        NUMBER(18,2)   NOT NULL,
    url_recibo         VARCHAR2(1024) NOT NULL,       -- enlace S3 al recibo/pdf
    creado_en          TIMESTAMP WITH TIME ZONE
                       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_ventas_carrito FOREIGN KEY (carrito_id) REFERENCES eft_carrito (carrito_id)
);