openapi: 3.0.3
info:
  title: API Tienda
  description: API para gestión de tienda
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Servidor local

paths:
  /hello:
    get:
      summary: Endpoint de prueba
      description: Retorna un mensaje de saludo
      responses:
        '200':
          description: Mensaje de saludo exitoso
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, World!"

  /producto:
    get:
      summary: Obtener todos los productos
      description: Retorna una lista de todos los productos disponibles
      responses:
        '200':
          description: Lista de productos obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
    post:
      summary: Crear nuevo producto
      description: Crea un nuevo producto en el sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'

  /producto/{id}:
    get:
      summary: Obtener producto por ID
      description: Retorna un producto específico basado en su ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Producto encontrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Producto no encontrado
    put:
      summary: Actualizar producto
      description: Actualiza un producto existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Producto no encontrado
    delete:
      summary: Eliminar producto
      description: Elimina un producto del sistema
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Producto eliminado exitosamente
        '404':
          description: Producto no encontrado

  /carro:
    get:
      summary: Obtener todos los carros
      description: Retorna una lista de todos los carros
      responses:
        '200':
          description: Lista de carros obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Carro'
    post:
      summary: Crear nuevo carro
      description: Crea un nuevo carro de compras
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Carro'
      responses:
        '201':
          description: Carro creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Carro'

  /carro/{id}:
    get:
      summary: Obtener carro por ID de usuario
      description: Retorna el carro de compras de un usuario específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Carro obtenido exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Carro'
        '404':
          description: Carro no encontrado
    put:
      summary: Actualizar carro
      description: Actualiza un carro existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Carro'
      responses:
        '200':
          description: Carro actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Carro'
        '404':
          description: Carro no encontrado
    delete:
      summary: Eliminar carro
      description: Elimina un carro del sistema
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Carro eliminado exitosamente
        '404':
          description: Carro no encontrado

  /usuario:
    get:
      summary: Obtener todos los usuarios
      description: Retorna una lista de todos los usuarios
      responses:
        '200':
          description: Lista de usuarios obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
    post:
      summary: Crear nuevo usuario
      description: Crea un nuevo usuario en el sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'

  /usuario/{id}:
    get:
      summary: Obtener usuario por ID
      description: Retorna un usuario específico basado en su ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Usuario encontrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuario no encontrado
    put:
      summary: Actualizar usuario
      description: Actualiza un usuario existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '200':
          description: Usuario actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuario no encontrado
    delete:
      summary: Eliminar usuario
      description: Elimina un usuario del sistema
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Usuario eliminado exitosamente
        '404':
          description: Usuario no encontrado

components:
  schemas:
    Producto:
      type: object
      properties:
        productoId:
          type: integer
          format: int64
        nombre:
          type: string
        descripcion:
          type: string
        stockActual:
          type: integer
          format: int64
        registroFecha:
          type: string
          format: date
        valorCosto:
          type: integer
          format: int64
        valorVenta:
          type: integer
          format: int64
        imagenUri:
          type: string

    Carro:
      type: object
      properties:
        carroId:
          type: integer
          format: int64
        usuarioId:
          type: string
        productoId:
          type: integer
          format: int64
        cantidad:
          type: integer
          format: int64
        registroFecha:
          type: string
          format: date
        vigenciaFlag:
          type: integer
        ticketId:
          type: integer

    Usuario:
      type: object
      properties:
        usuarioId:
          type: integer
          format: int64
        email:
          type: string
        nombre:
          type: string
        loginUltimo:
          type: string
          format: date-time

    Ticket:
      type: object
      properties:
        ticketId:
          type: integer
          format: int64
        total:
          type: string
        registroFecha:
          type: string
          format: date 